name: lint-clang-format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mrjimenez/clang-format-lint-action@v0.21
    #- uses: DoozyX/clang-format-lint-action@v0.20
    #- uses: d-griet/clang-format-lint-action@99a106be2f3f1a92d9783ea7c744fde62d8ce1fa
      with:
        source: './upnp ./ixml'
        extensions: 'h,c,cpp'
        clangFormatVersion: 19
