name: lint-clang-format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './upnp ./ixml'
        extensions: 'h,c,cpp'
